# Generated by Django 5.2.4 on 2025-07-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BogieChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(max_length=100)),
                ('inspection_by', models.CharField(max_length=100)),
                ('inspection_date', models.DateField()),
                ('bogie_details', models.JSONField()),
                ('bogie_checksheet', models.JSONField()),
                ('bmbc_checksheet', models.JSONField()),
            ],
        ),
    ]
